( - )
(2-
(2-1
(2-3)
(2-6),
(3-
(3-1
(3-1)
(3-2
(3-20)
(3-3
(3-35)
(3-38)
(3-39)
(Cuarzo)
(Explosivo\Modificar
(Grafito)
(K)
(Np=Ne
(de
(g/cm
(g/mol)
(g/mol),
(g/mol),  es  el 
(kcal/kg), 
(kcal/mol)
(kg/m
(mol/kg),   moles  de  productos  gaseosos.
(mol/kg),  Cantidad  de  producto  j,  formada  en  la  reacción  de  explosión.
(mol/kg),  es  la  cantidad  de  gases  producida  en  la  detonación.
(nº átomo),
(nº átomos),  Es  el 
(véase
)  
)  Densidad  inicial  o  de  encartuchado.
)  y 
), 
+ nCO
,  
, en 
- La  velocidad de  los  productos  tiene 
-1/2
-Abrir  y  Guardar  ficheros 
-Manejo
-Para  buscar  un  reactivo:
-Para  seleccionar  uno  o  varios  compuestos:
.  
1 g/cm
1,013
1.00794
1/2
10.811
100
12.011
121.75
137.327
14.00674
15,9994
15.9994
18.9984
185.85
200.59
22.98977
24.305
26.98154
273,15
28.0855
298
2·nCO
3-1
3-2
3/2
30.97376
31-002
32.066
35.4527
39.0983
40.078
54.93805
55.847
58.9332
6000
63.546
79.904
9.01218
91.224
;        
= 1000  kg/m
> 6000
ACEPTAR:
AYUDA:
Acce
Almacena  los  datos  de  l
Archivo
Atómico
Aunque 
BOTÓN 
BOTÓN  ACEPTAR:
BOTÓN  AYUDA:
BOTÓN  CANCELAR: 
Balance  de 
Balance  de  oxígeno
Borra 
Busca
C (Grafito)
CANCELAR
Calor
Cambia 
Cantidad
Chapman-Jouguet
Coeficiente
Com
Como 
Consigue  pasar  al  diálogo  de 
Constante
Constante de equilibrio  K
Constante empírica:
Copia  el 
Ctrl +
Curva
Cálculo
DESCRIPCIÓN  DE
Datos 
Debido  a 
Densidad
Descri
Desde  este  cuadro  de  diálogo,  se  puede
Detonaciones
Detonación  ideal.
Débiles:
EDICIÓN  DE  TEXTO:
EDICIÓNES  DE  TEXTO:
EXPLOCAL
Ecuaciones
El 
El frente de   detonación se  aleja
Elemento
Elimina 
Emplea
En 
Energía
Es 
Español
Esta
Explocal
Factor
Figura
Forum
Fuentes:
Fuertes:
Fórmula
Generalidades
Guarda
Guardar
Hugoniot
II:
INTRO
Incremento
Introduce  el  dato  del 
Introducir  datos
JANAF
Jacobs
Jouguet
Kamlet
LISTA  DE  DATOS  DEL REACTIVO:
LISTA  DE  REACTIVOS
La 
Las 
Los
Masa atómica
Modificar
Muesta  esta  pantalla de ayuda.
Muestra  todos  los  datos  del  reactivo  que  tiene  el  cursor.
Muestra  todos  los  nombres  de  los  reactivos 
Nombre,  Fórmula,  Peso  molecular,  Energía  de  formación 
Nota   I
Nota  I
Nota I
O +
Observaci
Organiza  todas  las  ventanas  hijas
Para 
Para  conseguir  este  objetivo,  se  deben  emplear  los  siguientes  controles:
Peso
Preferencias
Presión
Proceso  de  explosión  en  el  cual 
Producto
Producto  de  explosión
Pulse
Pulse la  inicial  del  nombre  del  reactivo.
R=8,31441
REACTIVO
REACTIVO.DAT
Rankine
Rayleigh
Reactiva
Rectas
SELECCIONA
Se 
Se  activa  si  hay 
Según 
Si 
Siendo:
Sistema 
Son  su
Sup
Sust
TECLA  INTRO:
TEXTO:
Tabla
También  se  puede 
Temperatura
Tipos
Tsipkin,
UNE
UNE 31-002
Velocidad
Volumen
Volumen  normal  de  gases.
Vuelve  al
Vuelve  al  diálogo  anterior:
a  2  g/cm
a=22,33
abiertas
activa
además
adiabático
adicionales
admisibles
afecta
alcanza
aleja
almacena
anterior
apare
aparición
aplica
aplicable
aplicación
apreciar
aproximación
archivo
archivo  de  texto
asociado
atómic
aument
aunque
ayuda
ayuda.
añadir
balance
balance  de  oxígeno
basa
botón  izquierdo  del  ratón 
busca
búsqueda
cada
calcula
calculo
calor
calor  de  explosión
cambiar
cantidad
capacidad
caracter
características
carbonatos
carbono
caso
choque
ciertas
circunstancia
coeficiente
coincide
como
compatible
comple
componen
componente
comportamiento
composición
compr
compuesto
con
condiciones
condición
configurar
conseguir
conserva
considera
constante
constituye
cont
contenido
control  de  edición  de  texto
controles
correc
correspond
cuadro
cual
cualitativa
cualquier
cuantitativa
cuatro
cuenta
cursor.
curva
cálculo
código
dato
datos
de 
debe
deben
debido
decir
deduc
def
definición
deflagraciones
deflagración
del
denomina
densidad
densidad  inicial
depend
des
desc
desde
desea
determina
detonaciones
detonación
detonación.
diferencia
diferentes
difier
difusión
dimensiones
directorio
disco
disminu
dispone
distint
divide
diálogo
donde:
dos
débiles
dónde
ecuaciones
ecuación
edición
editor
ejemplo
el 
elecci
elemento
elementos
ellos.
empl
emplear
empírica
en  la  figura  son:   
en  la  memoria..
encartuchado
encontrar
encuentra
energétic
energía
entalpías
entre
equilibrio
equivale
es 
específic
esta
estado
estadístico
este
estequiométricos
estima
esto
estudi
está
excedentari
exclusivamente
exist
exotérmic
exp
experimental
explosiva
explosivo
explosivo.
explosión
explosión.
explosión:
expresiones
expresión
factor
falta
fenómenos
ficheros
figura
forma
formación
formad
forman
formar
frente
fuer
fuertes,
funcion
función
fórmula
g/cm
g/mol
gas
gaseosos
gases
genera
grado
grafito
gran
hay
hidrógeno
hija
hugoniot
iconos
ideal
ideales
igual
implica
importan
inclu
incomp
inconsistencia
incorpora
incógnita
independiente
indican
inf
información
inicial
instalación
instant
intacto
interna
intervalo
introduc
invierte
itera
izquierdo
junto
kg/m
kilo
kilogramo
las
liber
libre
limita
lineales
lista
los
marcado.
mas
materia
mayoritarios.
mayoría
mecánicas
mediante
medida
memoria..
menor
menos
menú
mezcla
miembro
modifica
molecular
moles
movimiento
mucho
muestr
más
másica
máxima
método
mínima
múltipl
nCO
nCO·nH
nCarbonatos
necesario
necesita
negativo
ning
nombre
norma
normales
nuev
nulo):
número
objetivo
obliga
observa
obten
obtenidos
obtiene
ocupa
onda
opciones
otra
otro
oxida
oxígeno
oxígeno  necesario
pantalla
para
parte
partida
partir
parámetro
pasa
pendiente
permite
pero
peso
plan
por
porcentajes
porcentual
portapapeles
posee
posi
posibilidad
posible
positivo
precis
prefer
presen
presión
primer
principal
problema
proceso
produce
produci
producto
productos
produzca
programa
propag
propiedades
proporciona
proporción
próximo
puede
pueden
puesto
puls
punto
que
que:
queda
químic
rama
ratón
reaccion
reacción
reactivo
reactivos
real
realidad
realiza
recta
recta  de  Rayleigh
referencia
relación
representa
resolución
resolverá
resolviendo
respecto
rest
resulta
resultados
rápido
régimen
se 
segundo
selecci
seleccionado
seleccionar
sentido
significa
sigu
siguiente
similar
simplifica
sin
sistema
sobra
sobre
sobre  el  compuesto  deseado ,  verá  como 
sol
solución
son
son:
sonido
sub
subsónicas
suficiente
sufrir
suma
supe
supone
suponiendo
suposición
sustancia
sustituy
sólidos
sólo
tabla
tabulados
tangencia
tangente
tanto
temperatura
ten
tercer
term
texto
teóric
tiene
todas
todo
todos
toma
trabaj
transforma
trata
tres
térmi
uardar
una
unidades
valores
variable
varios
velocidad
velocidad  de  detonación
ventana
volumen
vuelve
y  
y  la 
· kg
· nCO
·R·T
·mol
átomo),
átomos
óxidos
últim
únic
